default: &default                                                                                   
  adapter: postgresql                                                                               
  encoding: utf8                                                                                    
  pool: 5                                                                                           
  username:                                                                                         
  password:                                                                                         

development:                                                                                        
  <<: *default                                                                                      
  database: hackit_dev                                                                             

test:                                                                                               
  <<: *default                                                                                      
  database: hackit_test                                                                            

production:                                                                                         
  <<: *default                                                                                      
  database: hackit
